fragment DeploymentFields on DagsterCloudDeployment {
  deploymentId
  deploymentName
  deploymentType
  deploymentStatus
}

query ListDeployments {
  deployments {
    ...DeploymentFields
  }
}

mutation CreateDeployment($name: String!, $agentType: DeploymentAgentType!) {
  createDeployment(deploymentName: $name, deploymentAgentType: $agentType) {
    __typename
    ... on DagsterCloudDeployment {
      ...DeploymentFields
    }
  }
}

mutation DeleteDeployment($id: Int!) {
  deleteDeployment(deploymentId: $id) {
    __typename
  }
}
