query ListSecrets($secretName: String) {
  secretsOrError(secretName: $secretName) {
    __typename
    ... on Secrets {
      secrets {
        id
        secretName
        secretValue
        fullDeploymentScope
        allBranchDeploymentsScope
        specificBranchDeploymentScope
        localDeploymentScope
        locationNames
      }
    }
  }
}

mutation CreateSecret($secretName: String!, $secretValue: String!, $fullDeploymentScope: Boolean, $allBranchDeploymentsScope: Boolean, $specificBranchDeploymentScope: String, $localDeploymentScope: Boolean, $locationNames: [String]) {
  createSecret(
    secretName: $secretName
    secretValue: $secretValue
    scopes: {
      fullDeploymentScope: $fullDeploymentScope
      allBranchDeploymentsScope: $allBranchDeploymentsScope
      specificBranchDeploymentScope: $specificBranchDeploymentScope
      localDeploymentScope: $localDeploymentScope
    }
    locationNames: $locationNames
  ) {
    __typename
    ... on CreateOrUpdateSecretSuccess {
      secret {
        id
        secretName
        secretValue
        fullDeploymentScope
        allBranchDeploymentsScope
        specificBranchDeploymentScope
        localDeploymentScope
        locationNames
      }
    }
    ... on TooManySecretsError {
      message
    }
    ... on InvalidSecretInputError {
      message
    }
    ... on SecretAlreadyExistsError {
      message
    }
  }
}

mutation UpdateSecret($secretId: String!, $secretName: String!, $secretValue: String!, $fullDeploymentScope: Boolean, $allBranchDeploymentsScope: Boolean, $specificBranchDeploymentScope: String, $localDeploymentScope: Boolean, $locationNames: [String]) {
  updateSecret(
    secretId: $secretId
    secretName: $secretName
    secretValue: $secretValue
    scopes: {
      fullDeploymentScope: $fullDeploymentScope
      allBranchDeploymentsScope: $allBranchDeploymentsScope
      specificBranchDeploymentScope: $specificBranchDeploymentScope
      localDeploymentScope: $localDeploymentScope
    }
    locationNames: $locationNames
  ) {
    __typename
    ... on CreateOrUpdateSecretSuccess {
      secret {
        id
        secretName
        secretValue
        fullDeploymentScope
        allBranchDeploymentsScope
        specificBranchDeploymentScope
        localDeploymentScope
        locationNames
      }
    }
    ... on TooManySecretsError {
      message
    }
    ... on InvalidSecretInputError {
      message
    }
  }
}

mutation DeleteSecret($secretId: String!) {
  deleteSecret(secretId: $secretId) {
    __typename
    ... on DeleteSecretSuccess {
      secretId
    }
  }
}
