fragment TeamPermissionsFields on DagsterCloudTeamPermissions {
  team {
    id
  }
  organizationPermissionGrant {
    grant
    customRoleId
    deploymentScope
    deploymentId
  }
  allBranchDeploymentsPermissionGrant {
    grant
    customRoleId
    deploymentScope
    deploymentId
  }
  deploymentPermissionGrants {
    grant
    customRoleId
    deploymentScope
    deploymentId
    locationGrants {
      locationName
      grant
      customRoleId
    }
  }
}

query ListTeamGrants {
  teamPermissions {
    ...TeamPermissionsFields
  }
}

mutation SetTeamGrant(
  $teamId: String!
  $scope: PermissionDeploymentScope!
  $grant: PermissionGrant!
  $customRoleId: String
  $deploymentId: Int
  $locationGrants: [LocationScopedGrantInput!]
) {
  createOrUpdateTeamPermission(
    teamId: $teamId
    deploymentScope: $scope
    grant: $grant
    customRoleId: $customRoleId
    deploymentId: $deploymentId
    locationGrants: $locationGrants
  ) {
    __typename
    ... on CreateOrUpdateTeamPermissionSuccess {
      teamPermissions {
        ...TeamPermissionsFields
      }
    }
  }
}

mutation DeleteTeamGrant(
  $teamId: String!
  $scope: PermissionDeploymentScope!
  $deploymentId: Int
) {
  removeTeamPermission(
    teamId: $teamId
    deploymentScope: $scope
    deploymentId: $deploymentId
  ) {
    __typename
    ... on RemoveTeamPermissionSuccess {
      teamPermissions {
        team {
          id
        }
      }
    }
  }
}
