name: Acceptance Tests

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - "examples/**"
      - "internal/**"
      - ".github/**"

jobs:
  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    env:
      TF_ACC: "1"
      DAGSTER_CLOUD_ORGANIZATION: ${{ secrets.DAGSTER_CLOUD_ORGANIZATION }}
      DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run acceptance tests
        run: go test ./internal/provider/... -v -timeout 120m
